airlyUrl: 'https://airapi.airly.eu'
apikey: AIRLY_API_KEY
installationId: ID_OF_INSTALLATION
commandPath: switchbot_py_path
onButtonMac: on_mac
offButtonMac: off_mac
caqiTreshold: 75
checkIntervalInMinutes: 1
cleaningPause:
  days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
  startTime: '8:00'
  endTime: '16:00'