airlyUrl: 'https://airapi.airly.eu'
apikey: AIRLY_API_KEY
installationId: ID_OF_INSTALLATION
commandPath: switchbot_py_path
onButtonMac: on_mac
offButtonMac: off_mac
caqiTreshold: 75
checkIntervalInMinutes: 1